apiVersion: v1
kind: Pod
metadata:
  name: ifremer-roundtrip
  labels:
    tier: api
spec:
  containers:
  - name: sync
    imagePullPolicy: Always
    image: argovis/ifremer-sync:roundtrip
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 100Mi
        cpu: 100m
  restartPolicy: Never



